"""Type stubs for placeholder module - enables lambda-free expressions."""

from typing import Any, Generic, TypeVar

T = TypeVar("T")
R = TypeVar("R")

class PlaceholderExpression(Generic[T, R]):
    """A compiled expression that acts as Callable[[T], R]."""

    def __call__(self, x: T) -> R: ...

    # Attribute access returns new expression
    def __getattr__(self, name: str) -> PlaceholderExpression[Any, Any]: ...

    # Comparison operators - return predicate expressions
    def __eq__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...  # type: ignore[override]
    def __lt__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...
    def __le__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...
    def __gt__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...
    def __ge__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...

    # Arithmetic operators
    def __add__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __sub__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __mul__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __truediv__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __floordiv__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __mod__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...

class PlaceholderMethodProxy:
    """Captures method calls on placeholder expressions."""

    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> PlaceholderExpression[Any, Any]: ...

class Placeholder:
    """Lambda-free expression builder.

    Usage:
        _ > 5       # Callable[[Any], bool] - comparison
        _.name      # Callable[[Any], Any] - attribute access
        _ * 2       # Callable[[Any], Any] - arithmetic
        _.upper()   # Callable[[Any], Any] - method call
    """

    # Attribute access
    def __getattr__(self, name: str) -> PlaceholderExpression[Any, Any]: ...
    def __getitem__(self, key: Any) -> PlaceholderExpression[Any, Any]: ...

    # Comparison operators - return callable predicates
    def __eq__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...  # type: ignore[override]
    def __lt__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...
    def __le__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...
    def __gt__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...
    def __ge__(self, other: Any) -> PlaceholderExpression[Any, bool]: ...

    # Arithmetic operators
    def __add__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __radd__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __sub__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __rsub__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __mul__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __rmul__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __truediv__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __rtruediv__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __floordiv__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __rfloordiv__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __mod__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...
    def __pow__(self, other: Any) -> PlaceholderExpression[Any, Any]: ...

    # Unary operators
    def __neg__(self) -> PlaceholderExpression[Any, Any]: ...
    def __pos__(self) -> PlaceholderExpression[Any, Any]: ...
    def __abs__(self) -> PlaceholderExpression[Any, Any]: ...

# Global placeholder instance
_: Placeholder
