from typing import Any

def to_dict(value: Any) -> Any: ...
def from_dict(target: Any, data: Any) -> Any: ...
def variant_from_dict(cls: Any, data: Any) -> Any: ...
def to_json(value: Any, **kwargs: Any) -> str: ...
def from_json(target: Any, text: str | bytes | bytearray, **kwargs: Any) -> Any: ...

__all__ = ["to_dict", "from_dict", "variant_from_dict", "to_json", "from_json"]
