"""Type stubs for Effect and AsyncEffect monads."""

from typing import Any, Awaitable, Callable, Generic, TypeVar

from stolas.types.result import Result

T = TypeVar("T")
U = TypeVar("U")

class Effect(Generic[T]):
    """Lazy evaluation monad."""

    __match_args__: tuple[str, ...]

    def __init__(self, thunk: Callable[[], T]) -> None: ...
    @property
    def thunk(self) -> Callable[[], T]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[T], U]) -> "Effect[U]": ...
    def map(self, func: Callable[[T], U]) -> "Effect[U]": ...
    def bind(self, func: Callable[[T], "Effect[U]"]) -> "Effect[U]": ...
    def run(self) -> T: ...
    def as_result(self) -> "Effect[Result[T, Exception]]": ...
    def to_async(self) -> "AsyncEffect[T]": ...
    @staticmethod
    def pure(value: T) -> "Effect[T]": ...
    @staticmethod
    def defer(func: Callable[..., T], *args: Any, **kwargs: Any) -> "Effect[T]": ...
    @staticmethod
    def attempt(thunk: Callable[[], T]) -> "Effect[Result[T, Exception]]": ...

class AsyncEffect(Generic[T]):
    """Lazy async evaluation monad (sibling of Effect)."""

    __match_args__: tuple[str, ...]

    def __init__(self, factory: Callable[[], Awaitable[T]]) -> None: ...
    @property
    def factory(self) -> Callable[[], Awaitable[T]]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[T], U]) -> "AsyncEffect[U]": ...
    def map(self, func: Callable[[T], U]) -> "AsyncEffect[U]": ...
    def bind(self, func: Callable[[T], "AsyncEffect[U]"]) -> "AsyncEffect[U]": ...
    async def run(self) -> T: ...
    def as_result(self) -> "AsyncEffect[Result[T, Exception]]": ...
    @staticmethod
    def pure(value: T) -> "AsyncEffect[T]": ...
    @staticmethod
    def defer(
        coro_fn: Callable[..., Awaitable[T]], *args: Any, **kwargs: Any
    ) -> "AsyncEffect[T]": ...
    @staticmethod
    def attempt(
        coro_fn: Callable[..., Awaitable[T]], *args: Any, **kwargs: Any
    ) -> "AsyncEffect[Result[T, Exception]]": ...

def from_effect(effect: Effect[T]) -> AsyncEffect[T]: ...
def to_effect(ae: AsyncEffect[T]) -> Effect[T]: ...
