"""Type stubs for Effect monad."""

from typing import Any, Callable, Generic, TypeVar

T = TypeVar("T")
U = TypeVar("U")

class Effect(Generic[T]):
    """Lazy evaluation monad."""

    __match_args__: tuple[str, ...]

    def __init__(self, thunk: Callable[[], T]) -> None: ...
    @property
    def thunk(self) -> Callable[[], T]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[T], U]) -> "Effect[U]": ...
    def map(self, func: Callable[[T], U]) -> "Effect[U]": ...
    def bind(self, func: Callable[[T], "Effect[U]"]) -> "Effect[U]": ...
    def run(self) -> T: ...
    @staticmethod
    def pure(value: T) -> "Effect[T]": ...
    @staticmethod
    def defer(func: Callable[..., T], *args: Any, **kwargs: Any) -> "Effect[T]": ...
