"""Type stubs for Many monad."""

from typing import Any, Callable, Generic, Iterable, Iterator, TypeVar

T = TypeVar("T")
U = TypeVar("U")

class Many(Generic[T], Iterable[T]):
    """Collection monad - also acts as Iterable[T]."""

    __match_args__: tuple[str, ...]

    def __init__(self, items: Iterable[T]) -> None: ...
    @property
    def items(self) -> tuple[T, ...]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def __rshift__(self, func: Callable[[Any], Any]) -> Any: ...
    def map(self, func: Callable[[T], U]) -> "Many[U]": ...
    def bind(self, func: Callable[[T], "Many[U]"]) -> "Many[U]": ...
    def filter(self, predicate: Callable[[T], bool]) -> "Many[T]": ...
    def first(self) -> T | None: ...
    def last(self) -> T | None: ...
    def count(self) -> int: ...
    def is_empty(self) -> bool: ...
    @classmethod
    def pure(cls, value: T) -> "Many[T]": ...
    @classmethod
    def empty(cls) -> "Many[T]": ...
