"""Type stubs for Option monad."""

from typing import Any, Callable, Generic, TypeVar

T = TypeVar("T")
U = TypeVar("U")

class Some(Generic[T]):
    """Presence variant."""

    __match_args__: tuple[str, ...]

    def __init__(self, value: T) -> None: ...
    @property
    def value(self) -> T: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[T], Any]) -> "Some[Any] | _Nothing": ...
    def map(self, func: Callable[[T], U]) -> "Some[U]": ...
    def bind(
        self, func: Callable[[T], "Some[U] | _Nothing"]
    ) -> "Some[U] | _Nothing": ...
    def unwrap(self) -> T: ...
    def unwrap_or(self, default: T) -> T: ...
    def is_some(self) -> bool: ...
    def is_nothing(self) -> bool: ...

class _Nothing:
    """Absence singleton."""

    __match_args__: tuple[str, ...]

    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[Any], Any]) -> "_Nothing": ...
    def map(self, func: Callable[[Any], Any]) -> "_Nothing": ...
    def bind(self, func: Callable[[Any], Any]) -> "_Nothing": ...
    def unwrap(self) -> Any: ...
    def unwrap_or(self, default: T) -> T: ...
    def is_some(self) -> bool: ...
    def is_nothing(self) -> bool: ...

Nothing: _Nothing

Option = Some[T] | _Nothing
