"""Type stubs for Validated monad."""

from typing import Any, Callable, Generic, TypeVar

T = TypeVar("T")
U = TypeVar("U")
E = TypeVar("E")

class Valid(Generic[T]):
    """Valid variant."""

    __match_args__: tuple[str, ...]

    def __init__(self, value: T) -> None: ...
    @property
    def value(self) -> T: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[T], Any]) -> "Valid[Any] | Invalid[Any]": ...
    def map(self, func: Callable[[T], U]) -> "Valid[U]": ...
    def is_valid(self) -> bool: ...
    def is_invalid(self) -> bool: ...
    def combine(
        self, other: "Valid[U] | Invalid[E]"
    ) -> "Valid[tuple[T, U]] | Invalid[E]": ...

class Invalid(Generic[E]):
    """Invalid variant."""

    __match_args__: tuple[str, ...]

    def __init__(self, errors: list[E] | E) -> None: ...
    @property
    def errors(self) -> tuple[E, ...]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __rshift__(self, func: Callable[[Any], Any]) -> "Invalid[E]": ...
    def map(self, func: Callable[[Any], Any]) -> "Invalid[E]": ...
    def is_valid(self) -> bool: ...
    def is_invalid(self) -> bool: ...
    def combine(self, other: "Valid[Any] | Invalid[E]") -> "Invalid[E]": ...

Validated = Valid[T] | Invalid[E]
