"""Type stubs for the validation module."""

from typing import Any, Callable

from stolas.types.validated import Validated

Validator = Callable[[Any], Validated[Any, str]]

__all__ = [
    "Validator",
    "rule",
    "matches",
    "length",
    "between",
    "min_val",
    "max_val",
    "non_empty",
    "one_of",
    "all_of",
    "any_of",
]

def rule(predicate: Callable[[Any], bool], message: str) -> Validator: ...
def matches(pattern: str, message: str | None = ...) -> Validator: ...
def length(min: int | None = ..., max: int | None = ...) -> Validator: ...
def between(lo: Any, hi: Any) -> Validator: ...
def min_val(n: Any) -> Validator: ...
def max_val(n: Any) -> Validator: ...
def non_empty() -> Validator: ...
def one_of(*choices: Any) -> Validator: ...
def all_of(*validators: Validator) -> Validator: ...
def any_of(*validators: Validator) -> Validator: ...
